#!/bin/sh
# borramos los ficheros de certificados de los directorios de instalacion (solo si se purga el paquete)

case "$1" in
  remove)
    exit 0
    ;;

  purge)

if [ -d "/usr/lib/AutoFirma" ];
 then
 rm /usr/lib/AutoFirma/*
fi

if [ -d "/usr/share/AutoFirma" ];
 then
 rm /usr/share/AutoFirma/*
fi

if [ -d "/usr/local/share/ca-certificates/AutoFirma" ];
 then
 rm /usr/local/share/ca-certificates/AutoFirma/*
fi

update-ca-certificates --fresh

echo "Los datos de la aplicación Autofirma han sido eliminados"

    exit 0
  ;;

esac

